# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '3'

services:
###########################
# Setup the PHP container
###########################
    angular:
        container_name: ${NAME_NODEJS_CONTAINER}
        build: .docker/angular
        restart: always
        tty: true
        stdin_open: true
        depends_on:
            - mongo
        volumes:
            - ./project:/home/project:rw
            - ./projecttmp/logs/pm2:/root/.pm2/logs/:rw
            - ./projecttmp/logs/angular:/home/projecttmp/logs/angular:rw
        ports:
            - ${VALUE_NODEJS_PORT}:4200
    mongo:
        container_name: ${NAME_SGBD_CONTAINER}
        image: mongo
        volumes:
           - ./projecttmp/mongo_data:/data/db
        ports:
            - ${VALUE_SGBD_PORT}:27017
            
